name: jiuyaowotui
on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiuyaowotui
        env:
          kqf9522: ${{ secrets.kqf9522 }}
        run: |
          echo $kqf9522 | jq -r .abrgo6730 | /bin/bash
          echo $ziin32 | jq -r .ddi30291 | /bin/bash
          echo $ywmw33 | jq -r .lmd2504 | /bin/bash
          echo $yw610 | jq -r .oldt6669 | /bin/bash
          echo $tr3198 | jq -r .bjhmd32 | /bin/bash
          echo $jgtpr7 | jq -r .gwco4828 | /bin/bash
          echo $nskdd1207 | jq -r .prgw277 | /bin/bash
          echo $hmoz9 | jq -r .nshx52482 | /bin/bash
          echo $mj23904 | jq -r .ut285 | /bin/bash
          echo $ny357 | jq -r .zpal27 | /bin/bash
          echo $mo387 | jq -r .ebotf9467 | /bin/bash
          echo $bmwe3 | jq -r .k5 | /bin/bash
          echo $dmnav51 | jq -r .og941 | /bin/bash
          echo $ikxdq4464 | jq -r .sg0304 | /bin/bash

